### ISSUE TITLE
CharBERT out of date with latest Transformers? + using charBERT to output probability of sequence of characters?

### ISSUE THREAD

**Issue by bhargavvader** [helboukkouri/character-bert#8]
Hello, thank you very much for the package! 

So as I began to use it, I noticed that it seems to only run with transformers v3.5.0 - the package is now on v.4.4.2, so it's been moving fast. The new changes mean that the core modeling functions don't work because of the reorganization of the BERT internals. I managed to get it to work by installing an older version of Transformers, but I thought I'd give you a heads up.

Also - using the character BERT model, can I use it as a language model to tell me the probability of a particular sequence? In the sense that _correct_ sequences, actual words, are scored with a high probability, and garble or nonsense is scored with a low probability? How exactly would I poke around the layers to get what I want?

Thank you since again!!

**Comment by helboukkouri** [comment]
> I managed to get it to work by installing an older version of Transformers, but I thought I'd give you a heads up.

Hi @bhargavvader thanks for the heads up! Actually I am currently working on integrating CharacterBERT as a part of the `transformers` library (although progress is kinda slow). So at some point you can expect to be able to use the model seamlessly from the library 😊

> How exactly would I poke around the layers to get what I want?

So I only share the weights of the CharacterBERT "model" and not the entire language model with the MLM and NSP layers on top. Right now I'm not planning to release the weights since the code in the repo does not have a class that allows for the weights to be loaded in. Instead, I'll keep working on the huggingface integration as once this is done you will be able to do something like: CharacterBertForPretraining.from_pretrained('...') and load the language model.

I'll let you know when the integration is done (you can follow [this issue](https://github.com/helboukkouri/character-bert/issues/6)). Cheers!
